# Generated by Django 5.2.4 on 2025-08-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_location_alter_event_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
